version: '3'

services:
  dns-updater:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DNS_PROVIDER=${DNS_PROVIDER}
      - DOMAIN=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS}
      - PASSWORD=${PASSWORD}
      - INTERVAL=${INTERVAL}
    volumes:
      - .:/app
